language: node_js
node_js:
  - '8.10'
  - '10'
script:
  - npm run lint || true
  - npm run cover
matrix:
  allow_failures:
    - node_js: '10' # until lambda test lib is fixed
after_script:
  - npm run publish-coverage
